# Generated by Django 5.2.6 on 2025-09-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(null=True)),
                ('ranking', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('title_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SubText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('comments', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.posts')),
            ],
        ),
    ]
