# Generated by Django 5.2.6 on 2025-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
